sonar.projectKey=Vineco77_auth-service-fase-4
sonar.projectName=auth-service-fase-4
sonar.organization=Vineco77_auth-service-fase-4

# Caminhos do código
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**, dist/**, **/*.d.ts

# Configuração de testes
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Linguagem
sonar.language=ts
sonar.sourceEncoding=UTF-8