sonar.projectKey=Vineco77_auth-service-fase-4
sonar.projectName=11soat-fast-food-fase-3-lambda
sonar.projectVersion=1.0

# Diretórios importantes
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js

# Configuração de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Configurações gerais
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io

# Exclusões (opcional)
sonar.coverage.exclusions=**/handlers/**, **/node_modules/**, **/*.test.js